package:
  name: pyvegafem
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja

  host:
    - python
    - pip

  run:
    - python


test:
  imports:
    - pyvegafem
  source_files:
    - tests
  commands:
    - python tests/test.py

about:
  summary: python interface of VegaFEM built with pybind11.
  license_file: LICENSE
